[framework]
name = "SemirSuite"
version = "1.0.0"
log_level = "INFO"

[agents]
default_agent = "IdeaForge"
max_concurrent_agents = 5

[safety]
enable_monitoring = true
ban_list_path = "safety/ban_list.txt"

[model_paths]
model_weights = "models/model_weights/"

[routes]
base_url = "/api/v1"